package me.lesovoy.lenta.ui.sources

import android.app.Dialog
import android.os.Bundle
import android.text.Editable
import android.text.TextWatcher
import android.view.View
import androidx.core.content.ContextCompat
import androidx.fragment.app.DialogFragment
import androidx.lifecycle.lifecycleScope
import me.lesovoy.lenta.R
import me.lesovoy.lenta.data.nextcloud.NextcloudQrParser
import me.lesovoy.lenta.data.source.SourceClientFactory
import me.lesovoy.lenta.data.source.StorageSource
import me.lesovoy.lenta.data.source.StorageSourceManager
import me.lesovoy.lenta.data.source.StorageSourceNaming
import me.lesovoy.lenta.data.source.StorageSourceType
import me.lesovoy.lenta.databinding.DialogAddSourceBinding
import me.lesovoy.lenta.ui.scanner.QrScannerActivity
import com.google.android.material.dialog.MaterialAlertDialogBuilder
import com.journeyapps.barcodescanner.ScanContract
import kotlinx.coroutines.launch

class SourceEditDialog(
    private val existingSource: StorageSource? = null,
    private val onSourceSaved: ((StorageSource) -> Unit)? = null
) : DialogFragment() {

    private var _binding: DialogAddSourceBinding? = null
    private val binding get() = _binding!!

    private var selectedType: StorageSourceType = existingSource?.type ?: StorageSourceType.NEXTCLOUD
    private var currentOAuthToken: String = existingSource?.token.orEmpty()
    private var currentOAuthUsername: String = existingSource?.username.orEmpty()

    private var hasCustomName: Boolean = existingSource != null && existingSource.name.isNotBlank()
    private var lastAutoGeneratedName: String = ""
    private var isUpdatingNameProgrammatically = false

    private val qrScannerLauncher = registerForActivityResult(ScanContract()) { result ->
        if (result.contents != null) {
            handleScannedQr(result.contents)
        }
    }

    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        _binding = DialogAddSourceBinding.inflate(layoutInflater)

        setupSourceSelectionCards()
        setupTextWatchers()
        setupButtons()

        if (existingSource != null) {
            // Edit existing source mode: go straight to configuration form
            binding.llSourceTypeSelection.visibility = View.GONE
            binding.llSourceForm.visibility = View.VISIBLE
            binding.btnBackToSelection.visibility = View.GONE

            binding.tvDialogTitle.text = "Edit ${existingSource.type.displayName}"
            binding.tvDialogSubtitle.text = "Update connection settings and credentials"

            binding.etSourceName.setText(existingSource.name)
            binding.etServerUrl.setText(existingSource.serverUrl)
            binding.etUsername.setText(existingSource.username)
            binding.etPassword.setText(if (existingSource.token.isNotBlank()) existingSource.token else existingSource.password)
            binding.etSmbShare.setText(existingSource.share)
            binding.etSmbDomain.setText(existingSource.domain)
            if (existingSource.port > 0) {
                binding.etPort.setText(existingSource.port.toString())
            }
            binding.etRootPath.setText(existingSource.rootPath)
            currentOAuthToken = existingSource.token
            currentOAuthUsername = existingSource.username

            updateFieldVisibilities()
        } else {
            // Add new source mode: start with source type selection
            binding.llSourceTypeSelection.visibility = View.VISIBLE
            binding.llSourceForm.visibility = View.GONE
            binding.btnBackToSelection.visibility = View.VISIBLE
        }

        return MaterialAlertDialogBuilder(requireContext())
            .setView(binding.root)
            .create()
    }

    private fun setupSourceSelectionCards() {
        binding.cardSelectNextcloud.setOnClickListener {
            selectSourceType(StorageSourceType.NEXTCLOUD)
        }
        binding.cardSelectGdrive.setOnClickListener {
            selectSourceType(StorageSourceType.GOOGLE_DRIVE)
        }
        binding.cardSelectOnedrive.setOnClickListener {
            selectSourceType(StorageSourceType.ONEDRIVE)
        }
        binding.cardSelectWebdav.setOnClickListener {
            selectSourceType(StorageSourceType.WEBDAV)
        }
        binding.cardSelectSmb.setOnClickListener {
            selectSourceType(StorageSourceType.SMB)
        }
        binding.cardSelectFtp.setOnClickListener {
            selectSourceType(StorageSourceType.FTP)
        }

        binding.btnBackToSelection.setOnClickListener {
            binding.llSourceForm.visibility = View.GONE
            binding.llSourceTypeSelection.visibility = View.VISIBLE
            binding.tvTestStatus.visibility = View.GONE
        }

        binding.btnCancelSelection.setOnClickListener {
            dismiss()
        }
    }

    private fun selectSourceType(type: StorageSourceType) {
        selectedType = type
        binding.tvDialogTitle.text = "Add ${type.displayName}"
        binding.tvDialogSubtitle.text = when (type) {
            StorageSourceType.NEXTCLOUD -> "Connect to Nextcloud server or scan QR code"
            StorageSourceType.GOOGLE_DRIVE -> "Connect your Google Drive account"
            StorageSourceType.ONEDRIVE -> "Connect your Microsoft OneDrive account"
            StorageSourceType.WEBDAV -> "Connect to WebDAV server or ownCloud"
            StorageSourceType.SMB -> "Connect to local network share (SMB/CIFS)"
            StorageSourceType.FTP -> "Connect to FTP / SFTP file server"
            else -> "Enter connection credentials"
        }

        binding.llSourceTypeSelection.visibility = View.GONE
        binding.llSourceForm.visibility = View.VISIBLE
        binding.tvTestStatus.visibility = View.GONE

        updateFieldVisibilities()
        autoUpdateDisplayName()
    }

    private fun setupTextWatchers() {
        val watcher = object : TextWatcher {
            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {}
            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {}
            override fun afterTextChanged(s: Editable?) {
                autoUpdateDisplayName()
            }
        }

        binding.etServerUrl.addTextChangedListener(watcher)
        binding.etUsername.addTextChangedListener(watcher)
        binding.etSmbDomain.addTextChangedListener(watcher)
        binding.etSmbShare.addTextChangedListener(watcher)

        binding.etSourceName.addTextChangedListener(object : TextWatcher {
            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {}
            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {}
            override fun afterTextChanged(s: Editable?) {
                if (isUpdatingNameProgrammatically) return
                val currentText = s?.toString()?.trim().orEmpty()
                hasCustomName = currentText.isNotEmpty() && currentText != lastAutoGeneratedName
            }
        })
    }

    private fun autoUpdateDisplayName() {
        val serverUrl = binding.etServerUrl.text?.toString().orEmpty()
        val username = if (selectedType == StorageSourceType.GOOGLE_DRIVE || selectedType == StorageSourceType.ONEDRIVE) {
            currentOAuthUsername.ifBlank { binding.etUsername.text?.toString().orEmpty() }
        } else {
            binding.etUsername.text?.toString().orEmpty()
        }
        val domain = binding.etSmbDomain.text?.toString().orEmpty()
        val share = binding.etSmbShare.text?.toString().orEmpty()

        val generated = StorageSourceNaming.generateDisplayName(
            type = selectedType,
            serverUrl = serverUrl,
            username = username,
            domain = domain,
            share = share
        )

        val currentInput = binding.etSourceName.text?.toString()?.trim().orEmpty()
        if (!hasCustomName || currentInput.isEmpty() || currentInput == lastAutoGeneratedName) {
            lastAutoGeneratedName = generated
            isUpdatingNameProgrammatically = true
            binding.etSourceName.setText(generated)
            isUpdatingNameProgrammatically = false
        }
    }

    private fun updateFieldVisibilities() {
        when (selectedType) {
            StorageSourceType.NEXTCLOUD -> {
                binding.cardNextcloudQr.visibility = View.VISIBLE
                binding.llOauthContainer.visibility = View.GONE
                binding.tilServerUrl.visibility = View.VISIBLE
                binding.tilUsername.visibility = View.VISIBLE
                binding.tilPassword.visibility = View.VISIBLE
                binding.tilServerUrl.hint = "Server URL (e.g. https://cloud.example.com)"
                binding.tilUsername.hint = "Username"
                binding.tilPassword.hint = "Password / App Token"
                binding.tilSmbShare.visibility = View.GONE
                binding.tilSmbDomain.visibility = View.GONE
                binding.tilPort.visibility = View.GONE
                binding.tilRootPath.visibility = View.GONE
            }
            StorageSourceType.GOOGLE_DRIVE -> {
                binding.cardNextcloudQr.visibility = View.GONE
                binding.llOauthContainer.visibility = View.VISIBLE
                binding.tilServerUrl.visibility = View.GONE
                binding.tilUsername.visibility = View.GONE
                binding.tilPassword.visibility = View.GONE
                binding.tilSmbShare.visibility = View.GONE
                binding.tilSmbDomain.visibility = View.GONE
                binding.tilPort.visibility = View.GONE
                binding.tilRootPath.visibility = View.GONE

                binding.tvOauthInfo.text = "Sign in to Google Drive in your web browser without entering access tokens manually."
                binding.btnOauthWebLogin.setIconResource(R.drawable.ic_google_drive)

                if (currentOAuthToken.isNotBlank()) {
                    binding.cardOauthAccount.visibility = View.VISIBLE
                    binding.tvOauthAccountName.text = currentOAuthUsername.ifBlank { "Google Account" }
                    binding.tvOauthAccountStatus.text = "Google Drive Authenticated"
                    binding.btnOauthWebLogin.text = "Switch Google Account"
                } else {
                    binding.cardOauthAccount.visibility = View.GONE
                    binding.btnOauthWebLogin.text = "Sign in with Google"
                }
            }
            StorageSourceType.ONEDRIVE -> {
                binding.cardNextcloudQr.visibility = View.GONE
                binding.llOauthContainer.visibility = View.VISIBLE
                binding.tilServerUrl.visibility = View.GONE
                binding.tilUsername.visibility = View.GONE
                binding.tilPassword.visibility = View.GONE
                binding.tilSmbShare.visibility = View.GONE
                binding.tilSmbDomain.visibility = View.GONE
                binding.tilPort.visibility = View.GONE
                binding.tilRootPath.visibility = View.GONE

                binding.tvOauthInfo.text = "Sign in to Microsoft OneDrive in your web browser without entering access tokens manually."
                binding.btnOauthWebLogin.setIconResource(R.drawable.ic_onedrive)

                if (currentOAuthToken.isNotBlank()) {
                    binding.cardOauthAccount.visibility = View.VISIBLE
                    binding.tvOauthAccountName.text = currentOAuthUsername.ifBlank { "Microsoft Account" }
                    binding.tvOauthAccountStatus.text = "OneDrive Authenticated"
                    binding.btnOauthWebLogin.text = "Switch Microsoft Account"
                } else {
                    binding.cardOauthAccount.visibility = View.GONE
                    binding.btnOauthWebLogin.text = "Sign in with Microsoft"
                }
            }
            StorageSourceType.SMB -> {
                binding.cardNextcloudQr.visibility = View.GONE
                binding.llOauthContainer.visibility = View.GONE
                binding.tilServerUrl.visibility = View.VISIBLE
                binding.tilUsername.visibility = View.VISIBLE
                binding.tilPassword.visibility = View.VISIBLE
                binding.tilServerUrl.hint = "Server Host / IP (e.g. 192.168.1.100)"
                binding.tilUsername.hint = "Username"
                binding.tilPassword.hint = "Password"
                binding.tilSmbShare.visibility = View.VISIBLE
                binding.tilSmbDomain.visibility = View.VISIBLE
                binding.tilPort.visibility = View.VISIBLE
                binding.tilRootPath.visibility = View.GONE
            }
            StorageSourceType.FTP -> {
                binding.cardNextcloudQr.visibility = View.GONE
                binding.llOauthContainer.visibility = View.GONE
                binding.tilServerUrl.visibility = View.VISIBLE
                binding.tilUsername.visibility = View.VISIBLE
                binding.tilPassword.visibility = View.VISIBLE
                binding.tilServerUrl.hint = "FTP Host / Server (e.g. ftp.example.com)"
                binding.tilUsername.hint = "Username"
                binding.tilPassword.hint = "Password"
                binding.tilSmbShare.visibility = View.GONE
                binding.tilSmbDomain.visibility = View.GONE
                binding.tilPort.visibility = View.VISIBLE
                binding.tilRootPath.visibility = View.GONE
            }
            StorageSourceType.WEBDAV, StorageSourceType.LOCAL -> {
                binding.cardNextcloudQr.visibility = View.GONE
                binding.llOauthContainer.visibility = View.GONE
                binding.tilServerUrl.visibility = View.VISIBLE
                binding.tilUsername.visibility = View.VISIBLE
                binding.tilPassword.visibility = View.VISIBLE
                binding.tilServerUrl.hint = "WebDAV Server URL (e.g. https://dav.example.com)"
                binding.tilUsername.hint = "Username (Optional)"
                binding.tilPassword.hint = "Password / Token (Optional)"
                binding.tilSmbShare.visibility = View.GONE
                binding.tilSmbDomain.visibility = View.GONE
                binding.tilPort.visibility = View.GONE
                binding.tilRootPath.visibility = View.VISIBLE
            }
        }
    }

    private fun launchQrScanner() {
        val options = QrScannerActivity.createScanOptions(getString(R.string.scan_qr_prompt))
        qrScannerLauncher.launch(options)
    }

    private fun handleScannedQr(rawContent: String) {
        val creds = NextcloudQrParser.parse(rawContent)
        if (creds != null) {
            selectedType = StorageSourceType.NEXTCLOUD
            updateFieldVisibilities()
            binding.etServerUrl.setText(creds.serverUrl)
            binding.etUsername.setText(creds.username)
            binding.etPassword.setText(creds.password)
            hasCustomName = false
            autoUpdateDisplayName()
            testConnection()
        } else {
            binding.tvTestStatus.visibility = View.VISIBLE
            binding.tvTestStatus.text = getString(R.string.qr_scan_invalid)
            binding.tvTestStatus.setTextColor(ContextCompat.getColor(requireContext(), android.R.color.holo_red_dark))
        }
    }

    private fun buildSourceFromForm(): StorageSource {
        val serverUrl = binding.etServerUrl.text?.toString()?.trim().orEmpty()
        val usernameInput = binding.etUsername.text?.toString()?.trim().orEmpty()
        val passwordInput = binding.etPassword.text?.toString()?.trim().orEmpty()
        val share = binding.etSmbShare.text?.toString()?.trim().orEmpty()
        val domain = binding.etSmbDomain.text?.toString()?.trim().orEmpty()
        val port = binding.etPort.text?.toString()?.toIntOrNull() ?: 0
        val rootPath = binding.etRootPath.text?.toString()?.trim().orEmpty()

        val isOAuthType = selectedType == StorageSourceType.GOOGLE_DRIVE || selectedType == StorageSourceType.ONEDRIVE

        val token = if (isOAuthType) {
            currentOAuthToken
        } else ""

        val username = if (isOAuthType) {
            currentOAuthUsername.ifBlank { usernameInput }
        } else {
            usernameInput
        }

        val password = if (!isOAuthType) {
            passwordInput
        } else ""

        val name = binding.etSourceName.text?.toString()?.trim().orEmpty().ifBlank {
            StorageSourceNaming.generateDisplayName(
                type = selectedType,
                serverUrl = serverUrl,
                username = username,
                domain = domain,
                share = share
            )
        }

        return StorageSource(
            id = existingSource?.id ?: "",
            name = name,
            type = selectedType,
            serverUrl = serverUrl,
            username = username,
            password = password,
            token = token,
            domain = domain,
            share = share,
            port = port,
            rootPath = rootPath,
            showHidden = existingSource?.showHidden ?: false,
            isDefault = existingSource?.isDefault ?: false
        )
    }

    private fun setupButtons() {
        binding.btnScanQrNextcloud.setOnClickListener {
            launchQrScanner()
        }

        binding.btnCancelSource.setOnClickListener {
            if (existingSource == null) {
                binding.llSourceForm.visibility = View.GONE
                binding.llSourceTypeSelection.visibility = View.VISIBLE
                binding.tvTestStatus.visibility = View.GONE
            } else {
                dismiss()
            }
        }

        binding.btnTestSource.setOnClickListener {
            testConnection()
        }

        binding.btnOauthWebLogin.setOnClickListener {
            OAuthWebLoginDialog.show(parentFragmentManager, selectedType) { token, accountName ->
                currentOAuthToken = token
                currentOAuthUsername = accountName
                updateFieldVisibilities()
                autoUpdateDisplayName()
                testConnection()
            }
        }

        binding.btnOauthDisconnect.setOnClickListener {
            currentOAuthToken = ""
            currentOAuthUsername = ""
            binding.tvTestStatus.visibility = View.GONE
            updateFieldVisibilities()
            autoUpdateDisplayName()
        }

        binding.btnSaveSource.setOnClickListener {
            val source = buildSourceFromForm()
            val manager = StorageSourceManager(requireContext())
            val saved = manager.saveSource(source)
            onSourceSaved?.invoke(saved)
            dismiss()
        }
    }

    private fun testConnection() {
        val source = buildSourceFromForm()
        binding.tvTestStatus.visibility = View.VISIBLE
        binding.tvTestStatus.text = "Testing connection to ${source.type.displayName}…"
        binding.tvTestStatus.setTextColor(ContextCompat.getColor(requireContext(), R.color.teal_700))

        lifecycleScope.launch {
            val client = SourceClientFactory.getClient(requireContext(), source)
            val result = client.testConnection()
            if (result.isSuccess) {
                binding.tvTestStatus.text = "Connected successfully!"
                binding.tvTestStatus.setTextColor(ContextCompat.getColor(requireContext(), R.color.teal_700))
            } else {
                val error = result.exceptionOrNull()?.message ?: "Unknown connection error"
                binding.tvTestStatus.text = "Connection failed: $error"
                binding.tvTestStatus.setTextColor(ContextCompat.getColor(requireContext(), android.R.color.holo_red_dark))
            }
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }

    companion object {
        const val TAG = "SourceEditDialog"

        fun show(
            fragmentManager: androidx.fragment.app.FragmentManager,
            existingSource: StorageSource? = null,
            onSourceSaved: ((StorageSource) -> Unit)? = null
        ) {
            SourceEditDialog(existingSource, onSourceSaved).show(fragmentManager, TAG)
        }
    }
}
